# Generated by Django 5.1.1 on 2024-09-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('ocupacion', models.CharField(max_length=100)),
            ],
        ),
    ]
