# Generated by Django 5.1.1 on 2024-09-13 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitido_por', models.CharField(max_length=255)),
                ('ocupacion', models.CharField(max_length=255)),
                ('hijos', models.IntegerField()),
                ('medicamentos', models.TextField()),
                ('enfermedades', models.TextField()),
                ('cx', models.TextField()),
                ('motivo_consulta', models.TextField()),
                ('cejas_anteriores', models.BooleanField(default=False)),
                ('lineas_anteriores', models.BooleanField(default=False)),
                ('labios_anteriores', models.BooleanField(default=False)),
                ('tiempo_anteriores', models.BooleanField(default=False)),
                ('tiempo_elaborado', models.CharField(max_length=255)),
                ('color_anterior', models.CharField(max_length=255)),
                ('alergias', models.TextField()),
                ('observaciones', models.TextField()),
                ('correcciones', models.TextField()),
                ('cejas_actuales', models.BooleanField(default=False)),
                ('color_actual', models.CharField(max_length=255)),
                ('neutralizar', models.BooleanField(default=False)),
                ('lineas_superior', models.BooleanField(default=False)),
                ('lineas_inferior', models.BooleanField(default=False)),
                ('labios_actuales', models.BooleanField(default=False)),
                ('anestesia_topica', models.BooleanField(default=False)),
                ('anestesia_inyectada', models.BooleanField(default=False)),
                ('material_desechable', models.CharField(max_length=255)),
                ('resultado_satisfactorio', models.TextField()),
                ('costo_maquillaje', models.IntegerField()),
                ('retoque_fecha', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
