# Generated by Django 5.1.1 on 2024-09-17 01:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_maquillaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
