# Generated by Django 5.1.1 on 2024-09-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_maquillaje', '0003_alter_historiaclinica_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='alergias',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='color_actual',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='color_anterior',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='correcciones',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='cx',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='enfermedades',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='material_desechable',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='medicamentos',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='motivo_consulta',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='observaciones',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='ocupacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='remitido_por',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='resultado_satisfactorio',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='tiempo_elaborado',
            field=models.CharField(max_length=100),
        ),
    ]
