# Generated by Django 5.1.1 on 2024-09-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_maquillaje', '0004_alter_historiaclinica_alergias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='alergias',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='color_actual',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='color_anterior',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='correcciones',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='costo_maquillaje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='cx',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='enfermedades',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hijos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='material_desechable',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='medicamentos',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='motivo_consulta',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='observaciones',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='remitido_por',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='resultado_satisfactorio',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='retoque_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='tiempo_elaborado',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
