# Generated by Django 5.1.1 on 2024-09-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_maquillaje', '0005_alter_historiaclinica_alergias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='alergias',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='cejas_anteriores',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='correcciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='cx',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='enfermedades',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='labios_anteriores',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='lineas_anteriores',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='medicamentos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='motivo_consulta',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='resultado_satisfactorio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='tiempo_anteriores',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
